### ISSUE TITLE
Congrats guys – Creator of LeetHub

### ISSUE THREAD

**Issue by QasimWani** [BaekjoonHub/BaekjoonHub#121]
Just wanted to say congrats on getting over a thousand users on Baekjoon! See my latest [tweet](https://twitter.com/qasim31wani/status/1526758670775754752); a shoutout would be nice. Would love to learn more about what other features you have in the roadmap!

**Comment by flaxinger** [comment]
Hey it's been a while. Thanks to Leethub we've been able to grow pretty quickly.
Unfortunately I do not have a twitter account, which makes me wonder if retweeting would mean much; however, most BaekjoonHub users do use LeetHub to my knowledge.
We now support two platforms([Baekjoon](https://www.acmicpc.net/), [Programmers](https://programmers.co.kr/)) - sadly we're in a semi halt since the main developers just graduated and are applying for jobs.
One feature I want to share with you though, is the way we solved the "multi-push problem"(where the user can make multiple pushes without any changes to the code). For platforms that provide submission statistics(eg. Leetcode provides runtime and memory information per submission), we compare each submission before pushing the code to Github and push the most recent code if it is the "best code"(least runtime, memory, code length - priority in that order). This allows us to effectively prevent meaningless pushes to Github as the user may only push if he/she has improved on the previously pushed code. We also had a feature that pushed submissions for all solved problems but eventually had to stop it as it sent too many http requests to the platform.
Anyhow thanks for the visit. Congrat on the 10M usage!
